# CONFIG FILE FOR AN LID EXPERIMENT
source_data_dir: '/data/SBC_MFCC_NORM_1_13/'
source_speech_metadata: '/speech_cls/metadata/sbc_metadata_slavic.csv'
target_data_dir: '/data/GP_MFCC_NORM_1_13/'
target_speech_metadata: '/speech_cls/metadata/gp_metadata_slavic.csv'
model_save_dir: '/speech_cls/in_progress/'
pretrained_model: '10092020_17_53_48_domain_LID_2_gps_sbc_ConvEncoder_512_512_MFCC_10.pth'
seed: 1337
language_set: 'BUL HRV CZE POL RUS UKR'
num_samples: 1800
to_save_file: '/speech_cls/figures/tsne'
#
input_signal_params:
    feature_type: 'MFCC'
    max_num_frames: 384
    num_frames: 300
    sampling_rate: 16000
    sample_segment: True
    start_index: 0
    end_index: 13
#
encoder_arch:
    encoder_model: ConvEncoder
    spectral_dim: 13
    frame_dropout: True # either frame_dropout or feature_dropout can be True
    feature_dropout: False
    signal_dropout_prob: 0.0
    num_channels:
       - 128
       - 256
       - 512

    filter_sizes:
       - 5
       - 10
       - 10
    stride_steps:
       - 1
       - 1
       - 1
    pooling_type: 'max'
#
classifier_arch:
    num_classes: 6
    input_dim: 512
    hidden_dim: 512
    num_layers: 2
    unit_dropout: False
    dropout_prob: 0.0
#
aux_classifier_arch:
    num_classes: 2
    input_dim: 512
    hidden_dim: 1024
    num_layers: 3
    unit_dropout: False
    dropout_prob: 0.0
#
batch_size: 92
cuda: True
catch_keyboard_interrupt: True
reload_from_files: True
