preprocessed_data_dir: '/data/GP_FBANK_NORM_1_13/'
speech_metadata: '/speech_cls/metadata/gp_speech_data.csv'
model_state_file: '31082020_1800'
model_save_dir: 'in_progress/'
language_set: 'CZE RUS'
pos_lang: 'CZE'
neg_lang: 'RUS'
eval_samples: 250
seed: 1337
input_signal_params:
    feature_type: 'FBANK'
    signal_masking: 'gen_pCZ_nRU_mfsc_0_13c_fr_shuffle'
    max_num_frames: 384
    num_frames: 300
    sampling_rate: 16000
    sample_segment: True
    start_index: 0
    end_index: 13
model_arch:
    nn_model: ConvNet
    feature_dim: 13
    num_classes: 2
    bottleneck: True
    bottleneck_size: 512
    output_dim: 512
    frame_dropout: True
    feature_dropout: False
    signal_dropout_prob: 0.0
    num_channels:
       - 128
       - 256
       - 512
    filter_sizes:
       - 5
       - 10
       - 10
    stride_steps:
       - 1
       - 1
       - 1
    pooling_type: 'max'
training_hyperparams:
    learning_rate: 0.001
    batch_size: 128
    num_epochs: 100
    early_stopping_criteria: 50
cuda: True
catch_keyboard_interrupt: True
reload_from_files: False
expand_filepaths_to_save_dir: True
